version: "3"
services:
  backend:
    build: .
    command: uvicorn deeprtc.main:app --host 0.0.0.0 --port 80
    volumes:
      - ./:/app
    network_mode: host
    depends_on:
      - worker
      - mongodb

  mongodb:
    image: mongo:5.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_PASSWORD}"
      MONGO_INITDB_DATABASE: "${MONGO_DATABASE}"
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - ./var/db.data/data:/data/db:delegated
      - ./var/db.data/dump:/docker-entrypoint-initdb.d:delegated

  worker:
    build: .
    command: celery -A deeprtc.main:celery_app worker -P solo --loglevel=info --logfile=celery.log
    volumes:
      - ./:/app
    environment:
      CELERY_BROKER_URL: "redis://localhost:6379/0"
      CELERY_RESULT_BACKEND: "redis://localhost:6379/0"
    network_mode: host
    depends_on:
      - redis
      - mongodb

  dashboard:
    build: .
    command: celery -A deeprtc.main:celery_app flower --port=5566
    environment:
      CELERY_BROKER_URL: "redis://localhost:6379/0"
      CELERY_RESULT_BACKEND: "redis://localhost:6379/0"
    network_mode: host
    depends_on:
      - redis
      - worker

  spellchecker:
    image: deeppavlov/base-cpu
    volumes:
      - ./var/dp_components:/root/.deeppavlov:delegated
      - ./var/dp_envs:/venv:delegated
    environment:
      CONFIG: "levenshtein_corrector_ru"
    ports:
      - 5000:5000

  redis:
    image: redis:6-alpine
    ports:
      - 6379:6379
